# Generated by Django 5.0.2 on 2025-05-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('GUEST', 'Guest'), ('HOST', 'Host')], default='GUEST', max_length=10),
        ),
    ]
